version: '3.8'

services:
  sinusbot:
    build: .
    container_name: sinusbot-ts6
    restart: unless-stopped
    ports:
      - "8087:8087"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/opt/sinusbot/data
      - ./scripts:/opt/sinusbot/scripts
    environment:
      - DISPLAY=:99
